// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZj7uR381bcLdwfcBI_BozGVHhIAEa7xs',
    appId: '1:584140094374:web:3882066aa62b8d9e73ad67',
    messagingSenderId: '584140094374',
    projectId: 'guard-12345',
    authDomain: 'guard-12345.firebaseapp.com',
    storageBucket: 'guard-12345.firebasestorage.app',
    measurementId: 'G-MLGTVXJ40N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAweb8bgxejbineER-Znv0WQjV07yYdGwE',
    appId: '1:584140094374:android:5f5488ac661f0c1b73ad67',
    messagingSenderId: '584140094374',
    projectId: 'guard-12345',
    storageBucket: 'guard-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDufHZG0_zY03gx5XN3mtoCxywJ6oU5C_0',
    appId: '1:584140094374:ios:ac5c2f4b554b36d473ad67',
    messagingSenderId: '584140094374',
    projectId: 'guard-12345',
    storageBucket: 'guard-12345.firebasestorage.app',
    androidClientId: '584140094374-s61s45mfusafq6q0m6qb3j39t7t87csc.apps.googleusercontent.com',
    iosClientId: '584140094374-sa2gjtvkt4v0n9i1orih1f6iau6u4t1n.apps.googleusercontent.com',
    iosBundleId: 'guard.com.guard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDufHZG0_zY03gx5XN3mtoCxywJ6oU5C_0',
    appId: '1:584140094374:ios:ac5c2f4b554b36d473ad67',
    messagingSenderId: '584140094374',
    projectId: 'guard-12345',
    storageBucket: 'guard-12345.firebasestorage.app',
    androidClientId: '584140094374-s61s45mfusafq6q0m6qb3j39t7t87csc.apps.googleusercontent.com',
    iosClientId: '584140094374-sa2gjtvkt4v0n9i1orih1f6iau6u4t1n.apps.googleusercontent.com',
    iosBundleId: 'guard.com.guard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZj7uR381bcLdwfcBI_BozGVHhIAEa7xs',
    appId: '1:584140094374:web:3882066aa62b8d9e73ad67',
    messagingSenderId: '584140094374',
    projectId: 'guard-12345',
    authDomain: 'guard-12345.firebaseapp.com',
    storageBucket: 'guard-12345.firebasestorage.app',
    measurementId: 'G-MLGTVXJ40N',
  );
}
